package nft

const (
	NFTNL_SET_TABLE = iota
	NFTNL_SET_NAME
	NFTNL_SET_FLAGS
	NFTNL_SET_KEY_TYPE
	NFTNL_SET_KEY_LEN
	NFTNL_SET_DATA_TYPE
	NFTNL_SET_DATA_LEN
	NFTNL_SET_FAMILY
	NFTNL_SET_ID
	NFTNL_SET_POLICY
	NFTNL_SET_DESC_SIZE
	NFTNL_SET_TIMEOUT
	NFTNL_SET_GC_INTERVAL
	NFTNL_SET_USERDATA
	NFTNL_SET_OBJ_TYPE
	__NFTNL_SET_MAX
)
