package nft
import "syscall"

const (
	NFT_MSG_NEWTABLE = iota
	NFT_MSG_GETTABLE
	NFT_MSG_DELTABLE
	NFT_MSG_NEWCHAIN
	NFT_MSG_GETCHAIN
	NFT_MSG_DELCHAIN
	NFT_MSG_NEWRULE
	NFT_MSG_GETRULE
	NFT_MSG_DELRULE
	NFT_MSG_NEWSET
	NFT_MSG_GETSET
	NFT_MSG_DELSET
	NFT_MSG_NEWSETELEM
	NFT_MSG_GETSETELEM
	NFT_MSG_DELSETELEM
	NFT_MSG_NEWGEN
	NFT_MSG_GETGEN
	NFT_MSG_TRACE
	NFT_MSG_NEWOBJ
	NFT_MSG_GETOBJ
	NFT_MSG_DELOBJ
	NFT_MSG_GETOBJ_RESET
	NFT_MSG_MAX
)

const (
	MNL_CB_ERROR  =  -1
	MNL_CB_STOP   =  0
	MNL_CB_OK     =  1
)

//const (
//	NLMSG_ERROR = 0x2 //syscall.NLMSG_ERROR
//)

const (
	//NLMSG_MIN_TYPE = syscall.NLMSG_MIN_TYPE
	NFNL_MSG_BATCH_BEGIN = syscall.NLMSG_MIN_TYPE
	NFNL_MSG_BATCH_END = syscall.NLMSG_MIN_TYPE+1
)

//const (
//	NLA_F_NESTED =     (1 << 15) //syscall.NLA_F_NESTED
//)
const (
    SizeofNfgenmsg      = 4 //maybe syscall.NLMSG_ALIGNTO
	NFNL_SUBSYS_NFTABLES = 10
)

//nf_tables data netlink attributes
const (
	NFTA_DATA_UNSPEC = iota
	NFTA_DATA_VALUE
	NFTA_DATA_VERDICT
	__NFTA_DATA_MAX
)

//nf_tables set element netlink attributes
const (
	NFTA_SET_ELEM_UNSPEC = iota
	NFTA_SET_ELEM_KEY
	NFTA_SET_ELEM_DATA
	NFTA_SET_ELEM_FLAGS
	NFTA_SET_ELEM_TIMEOUT
	NFTA_SET_ELEM_EXPIRATION
	NFTA_SET_ELEM_USERDATA
	NFTA_SET_ELEM_EXPR
	NFTA_SET_ELEM_PAD
	NFTA_SET_ELEM_OBJREF
	__NFTA_SET_ELEM_MAX
)

//nf_tables set element list netlink attributes
const (
	NFTA_SET_ELEM_LIST_UNSPEC = iota
	NFTA_SET_ELEM_LIST_TABLE
	NFTA_SET_ELEM_LIST_SET
	NFTA_SET_ELEM_LIST_ELEMENTS
	NFTA_SET_ELEM_LIST_SET_ID
	__NFTA_SET_ELEM_LIST_MAX
)


//nf_tables table netlink attributes
const (
	NFTA_TABLE_UNSPEC = iota
	NFTA_TABLE_NAME
	NFTA_TABLE_FLAGS
	NFTA_TABLE_USE
	__NFTA_TABLE_MAX
)
